### PR TITLE
Update tarsnap key

### LINKED ISSUE #65: Tarsnap packaging key is expired
The current key, located at https://github.com/lobsters/lobsters-ansible/blob/cb938831c4025213ccd58f7152c32e110c9e81f2/roles/tarsnap/files/tarsnap-deb-packaging-key.asc

Is expired. Running gpg on it shows:

```
pub   rsa4096 2017-02-04 [SC] [expired: 2018-02-01]
      28506A18C3F0BA4C870FC74940B98B68F04DE775
uid           Tarsnap .deb packages signing key (Tarsnap Backup Inc.) <pkg-deb@tarsnap.com>
```

### PR DESCRIPTION
**Pull request by shanemhansen**
Per directions at https://www.tarsnap.com/pkg-deb.html downloaded
a copy of https://pkg.tarsnap.com/tarsnap-deb-packaging-key.asc

The expired key causes the apt-get install of tarsnap to fail on a fresh server.

Fixes #65

### CODE REVIEW

**Comment by jstoja** [comment]
Hey @shanemhansen,

Doesn't it makes more sense to amend the role to download this file from the website directly?

Best,
Julien

**Comment by pushcx** [comment]
@shanemhansen Thanks for this patch. I've rolled it into some other ansible updates that I'll push soon.

@jstoja I agree that would be convenient, but I prefer the ~annual inconvenience of putting eyes on the new keys for a service that's getting a copy of all our data.

**Comment by shanemhansen** [comment]
Sorry for being unresponsive. I hope finding this was helpful. Thanks @pushcx !

**Comment by pushcx** [comment]
You have nothing to apologize for. Thanks for contributing.

**Pull request closed without merging**
