### PR TITLE
move mockturtle python code to top-level "mockturtle" directory.

### PR DESCRIPTION
**Pull request by alanpost**
Pull the bot out of the ansible directory structure and make it
top-level directory.  This is to facilitate testing.

This is an interstitial (work in progress) PR related to adding unit tests.

### CODE REVIEW

**Comment by hmadison** [comment]
@alanpost Can we consider making a top level mockturtle repo and having the code live there?

**Comment by alanpost** [comment]
I'm happy to do that.  Question, to be sure I understand: do we also move the IRC-specific ansible rules to this repository or leave them all in lobsters-ansible?

**Comment by alanpost** [comment]
@philsc, commit 6cad90d is the ansible work necessary to run sopel 7 in production.

**Comment by alanpost** [comment]
On the advice of @hmadison the mockturtle source code is now in it's own repository:

https://github.com/lobsters/mockturtle

**Pull request closed without merging**
